spring:
  datasource:
    url: jdbc:h2:mem:testDB; # testDB 라는 테스트 메모리 데이터 베이스 사용 (로컬 환경에 세팅 필요)
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console # H2 Console 접근 경로